//Grab the author parameter out of the URL and...
//use if to fetch that specific author from the placeholder data site
//Use the author parameter to fetch the specific post by...
//a specific author from the placeholder data site
//Name of author and posts by author should be displayed on the page
