//Grab the post id parameter out of the URL and...
//use it to fetch that specific post from the placeholder data site
//Use the post id parameter AND...
//use dot notation to access the autho name of that post within the first fetch
//Name of author, title of post and content of that post should be displayed on this page
